repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: check-ast
  - repo: local
    hooks:
      - id: sort_pyproject
        name: sort_pyproject
        entry: toml-sort -i --sort-table-keys --sort-inline-tables
        language: python
        files: ^pyproject\.toml$
        additional_dependencies: ["toml-sort==0.23.1"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff-format  # formatter
        types_or: [ python, pyi, jupyter ]
      - id: ruff  # linter
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.350
    hooks:
    - id: pyright
      additional_dependencies: [equinox, jax, jaxtyping]
